CREATE DATABASE REACT_TEST;
USE REACT_TEST;

CREATE TABLE PRODUCT(
	 PRO_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	 PRO_NAME VARCHAR(50), 
	 PRO_DESCRIPTION VARCHAR(200) NOT NULL, 
	 PRO_PRICE DECIMAL(10,2) NOT NULL, 
	 PRO_QUANTITY INT NOT NULL
 );
 
 -- INSERIR VALORES FICTÍCIOS PARA TESTE
 INSERT INTO PRODUCT (PRO_NAME, PRO_DESCRIPTION, PRO_PRICE, PRO_QUANTITY) 
	VALUES('Capivara de Chocolate', 'Capivara feita de chocolate branco e preto', 9.90, 250);
    
 INSERT INTO PRODUCT (PRO_NAME, PRO_DESCRIPTION, PRO_PRICE, PRO_QUANTITY) 
	VALUES('Capivarinha', 'Capivara com menos de 30cm', 19.90, 250);
 
 SELECT * FROM PRODUCT;
 
 -- ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';
 -- flush privileges;
 
 -- DROP DATABASE REACT_TEST;